// tailwind.config.js
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // ── Smart League Design System Colors ──
        "on-surface-variant": "#43474e",
        "surface-container": "#efedf1",
        "background": "#faf9fd",
        "outline-variant": "#c4c6cf",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#003d3d",
        "tertiary": "#002626",
        "inverse-surface": "#2f3033",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#ffe088",
        "on-secondary-fixed": "#241a00",
        "on-error-container": "#93000a",
        "outline": "#74777f",
        "primary-fixed-dim": "#a7c8ff",
        "on-tertiary-fixed": "#002020",
        "on-surface": "#1a1c1e",
        "tertiary-fixed-dim": "#5dd9d8",
        "inverse-primary": "#a7c8ff",
        "on-primary": "#ffffff",
        "surface-container-high": "#e9e7eb",
        "tertiary-fixed": "#7df5f5",
        "secondary-fixed-dim": "#e9c349",
        "on-background": "#1a1c1e",
        "inverse-on-surface": "#f1f0f4",
        "surface-dim": "#dad9dd",
        "surface": "#faf9fd",
        "on-primary-fixed-variant": "#1f477b",
        "on-primary-fixed": "#001b3c",
        "primary-fixed": "#d5e3ff",
        "secondary": "#735c00",
        "primary": "#002045",
        "on-tertiary-fixed-variant": "#004f4f",
        "on-tertiary-container": "#26b0b0",
        "surface-container-low": "#f4f3f7",
        "on-secondary-fixed-variant": "#574500",
        "primary-container": "#043669",
        "on-secondary-container": "#745c00",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "surface-tint": "#3a5f94",
        "on-primary-container": "#7ca0d9",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-bright": "#faf9fd",
        "surface-container-highest": "#e3e2e6",
        "surface-variant": "#e3e2e6",
        "secondary-container": "#fed65b",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        inter: ["Inter", "sans-serif"],
        manrope: ["Manrope", "sans-serif"],
      },
    },
  },
  plugins: [],
};
